- hosts: all

  gather_facts: False
  remote_user: admin
  vars:
    wp_mysql_db: "wordpress"
    wp_mysql_user: "admin"
    wp_mysql_password: "wordpress"
    wp_mysql_host: "terraform-20220211082115243200000001.cczxixzntjlx.eu-west-3.rds.amazonaws.com"
  tasks:
    - name: install python 3
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  roles:
    - server
    - php
    - filebeat
    - wordpress
    

