---
#  Installation de WP-CLI qui fourni une interface en ligne de commande pour administrer wordpress 
- name: Install WP-CLI
  become: true
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: a+x

# tasks file for wordpress
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Configure WordPress
  become: yes
  command: wp core config
    --path="/var/www/wordpress"
    --dbname="{{ wp_mysql_db }}"
    --dbuser="{{ wp_mysql_user }}"
    --dbpass="{{ wp_mysql_password }}"
    --dbhost="{{ wp_mysql_host }}"
    --allow-root

- name: Update default Apache site
  become: yes
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache
